# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'appdynamics_mobilesdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for appdynamics_mobilesdk
  pod 'AppDynamicsAgent'
  pod 'Flutter'
end
