# Uncomment the next line to define a global platform for your project
platform :ios, '14.5'

target 'appdynamics_agent' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for appdynamics_agent
  pod 'AppDynamicsAgent', '~> 2022.2'
  pod 'Flutter'
end
