target 'appdynamics_agent' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for appdynamics_agent
  pod 'AppDynamicsAgent', '~> 2023.10.1'
  pod 'Flutter'
end
