# cicd.yml is redundant with the updated dart.yml for Flutter CI. Recommend deprecating this file.
# Optionally, you may keep specialized jobs here if needed, but for now, disable all jobs.

name: cicd (deprecated)

on:
  workflow_dispatch:

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated. Use dart.yml for CI."
