# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart (Flutter)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Use Flutter instead of Dart for setup
      - uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      # Verify formatting
      - name: Verify formatting
        run: dart format . --set-exit-if-changed

      # Analyze project source
      - name: Analyze project source
        run: flutter analyze

      # Run tests (Flutter)
      - name: Run tests
        run: flutter test
